### ISSUE TITLE
rehype type error

### ISSUE THREAD

**Issue by swordow** [uiwjs/react-md-editor#518]
package.json is :
```
{
  "name": "sdt",
  "version": "1.0.0",
  "description": "sdt",
  "scripts": {
    "compile_jsx": "babel src -d dist",
    "build_dev": "webpack --mode development --config webpack.config.js --progress",
    "build": "webpack --mode production",
    "start_test": "webpack -d --watch",
    "start_hot": "webpack-dev-server --hot",
    "start": "webpack --mode production && webpack-dev-server --mode production --config webpack.config.js --progress",
    "start_dev": "webpack --mode development --config webpack.config.js --progress && webpack-dev-server --hot --mode development --config webpack.config.js --progress"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@uiw/react-md-editor": "^3.20.10",
    "antd": "^4.3.5",
    "axios": "^0.19.2",
    "clean-webpack-plugin": "^3.0.0",
    "es2015": "0.0.0",
    "html-webpack-plugin": "^4.3.0",
    "http-proxy-middleware": "^1.0.4",
    "mini-css-extract-plugin": "^0.12.0",
    "node-gyp": "^3.8.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-hot-loader": "^4.12.21",
    "react-router-dom": "^5.2.0",
    "ts-loader": "^6.2.2",
    "typescript": "^4.6.4"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.5",
    "babel-plugin-import": "^1.8.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-latest": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "css-loader": "^1.0.1",
    "file-loader": "^6.0.0",
    "html-loader": "^1.1.0",
    "image-webpack-loader": "^6.0.0",
    "less-loader": "^7.0.2",
    "sass-loader": "^9.0.1",
    "style-loader": "^0.23.1",
    "url-loader": "^4.1.0",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.0"
  }
}
```
and error is :
```
index.js:181 Uncaught TypeError: Expected usable value, not `data:application/javascript;charset=utf-8;base64,ZXhwb3J0IHtkZWZhdWx0fSBmcm9tICcuL2xpYi9pbmRleC5qcycK`
    at Function.use (index.js:181:13)
    at eval (index.js:11:132)
    at ./node_modules/rehype/index.js (admin.js:11591:1)
    at __webpack_require__ (admin.js:20:30)
    at eval (Markdown.js:7:64)
    at ./node_modules/@uiw/react-md-editor/esm/components/TextArea/Markdown.js (admin.js:582:1)
    at __webpack_require__ (admin.js:20:30)
    at eval (index.js:11:67)
    at ./node_modules/@uiw/react-md-editor/esm/components/TextArea/index.js (admin.js:629:1)
    at __webpack_require__ (admin.js:20:30)
```

node.js is v16.14.2

**Comment by jaywcjlove** [comment]
You can use [codesandbox.io](https://codesandbox.io/embed/markdown-editor-for-react-izdd6?fontsize=14&hidenavigation=1&theme=dark) to reproduce the error for me.


@swordow
