### ISSUE TITLE
Multiline code block crashing page

### ISSUE THREAD

**Issue by ntcnjl** [uiwjs/react-md-editor#559]
When using the ``` code block, the whole page crashes with multiple errors in the console:
```
react-dom.development.js:18687 The above error occurred in the <ReactMarkdown> component:

    at ReactMarkdown (https://website/static/js/bundle.js:233154:42)
    at div
    at https://website/static/js/bundle.js:38066:32
    at div
    at div
    at div
    at https://website/static/js/bundle.js:38452:70
    at div
    at AjaxElementLoader (https://website/static/js/bundle.js:933:143)
    at AjaxWidgetLoader (https://website/static/js/bundle.js:1041:143)
    at Note (https://website/static/js/bundle.js:14205:143)
    at ConnectFunction (https://website/static/js/bundle.js:159021:68)
    at div
    at div
    at Widget (https://website/static/js/bundle.js:9445:143)
    at div
    at Resizable (https://website/static/js/bundle.js:161498:35)
    at DraggableCore (https://website/static/js/bundle.js:150793:5)
    at GridItem (https://website/static/js/bundle.js:152323:5)
    at div
    at ReactGridLayout (https://website/static/js/bundle.js:153240:5)
    at ResponsiveReactGridLayout (https://website/static/js/bundle.js:154546:5)
    at WidthProvider (https://website/static/js/bundle.js:155303:7)
    at DashboardGrid (https://website/static/js/bundle.js:2490:143)
    at ConnectFunction (https://website/static/js/bundle.js:159021:68)
    at section
    at App (https://website/static/js/bundle.js:1317:143)
    at ConnectFunction (https://website/static/js/bundle.js:159021:68)
    at CatchError (https://website/static/js/bundle.js:2074:143)
    at Provider (https://website/static/js/bundle.js:158723:20)

React will try to recreate this component tree from scratch using the error boundary you provided, CatchError.

TypeError: N.entries is not a function
    at l (generator.js:304:1)
    at overload (index.js:173:1)
    at node (element<code>) (index.js:189:1)
    at node (element<pre>) (index.js:206:1)
    at node (root) (index.js:206:1)
    at visitParents (index.js:148:1)
    at visit (index.js:165:1)
    at generator.js:177:1
    at wrapped (index.js:115:1)
    at next (index.js:65:1) 
```

I am using the latest version with react 18.2.0, and have tried copying directly from the README and the error still occurs

**Comment by jaywcjlove** [comment]
<img width="912" alt="image" src="https://github.com/uiwjs/react-md-editor/assets/1680273/75ab1167-775c-414c-9d06-fefd170299e3">

I can't reproduce your error.

@ntcnjl

**Comment by ntcnjl** [comment]
Im using node 18.14.2, could that be causing issues?

**Comment by jaywcjlove** [comment]
<img width="318" alt="image" src="https://github.com/uiwjs/react-md-editor/assets/1680273/86bb05a9-746d-40bf-93ac-3274cd29e1bd">

@ntcnjl I can't reproduce your error

**Comment by jaywcjlove** [comment]
@ntcnjl If you can provide a reproducible example, I can help you take a look
